### PR TITLE
OOPS Concepts

### PR DESCRIPTION
**Pull request by yash1rj**
I will be adding more in some time.

### CODE REVIEW

**Comment by mraza007** [comment]
Wow Nice work 
We also need to add few stuff on decorators

**Comment by mraza007** [comment]
Hey make sure you add stuff to markdown version folder

**Comment by mraza007** [comment]
You forgot to link those files in README
Anyways Nice work 
but make sure you link those files in README

**Comment by yash1rj** [comment]
1>Not understanding what you mean by adding stuff to markdown version folder.
2>What to link and how.(readme)..?
3>Over the next few days I'll be adding more content
4>I do have something on decorators...I'll add that after OOPS.

**Comment by mraza007** [comment]
Hey look at the README how I structured

**Pull request merged**
